### ISSUE TITLE
tar: Unrecognized archive format

### ISSUE THREAD

**Issue by hydex86** [ursachec/CPAProxy#16]
I'm trying to build CPAProxy using 

$ ./scripts/build-all.sh

But this process exits with this error:

Making install in sample
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for`install-data-am'.
Making install in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for`install-data-am'.
~/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/build
mkdir: /Users/dani/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/built/i386/include/sys/: File exists
Building tor for i386...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   302  100   302    0     0     94      0  0:00:03  0:00:03 --:--:--    94
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by Catalyst085** [comment]
I am getting this issue :(

**Comment by chrisballinger** [comment]
@Catalyst085 On the latest commit to the master branch? Can you double-check that you can download the sources of the dependencies manually?

**Comment by Catalyst085** [comment]
Yup I have doubled check everything, followed all the instruction. The library is used on this git project
https://github.com/ChatSecure/ChatSecure-iOS

I face problem on this.

**Comment by xmgcs** [comment]
i am from china, i can not use it.
i run :
 bash /scripts/build-all.sh
but i have a error:
 /usr/local/bin/ginstall -c -m 644  ./event2/event-config.h '/Users/a1/Desktop/123/CPAProxy/scripts/build/iPhoneSimulator-11.2-i386/include/event2'
Making install in sample
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for `install-data-am'.
~/Desktop/123/CPAProxy/scripts/build
Building tor for i386...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to dist.torproject.org port 443: Operation timed out
1deMacBook-Pro-2:CPAProxy a1$ bash /Users/a1/Desktop/123/CPAProxy/scripts/build-all.sh
