### ISSUE TITLE
XCode 7 Compile error

### ISSUE THREAD

**Issue by xiongcaixing1986** [ursachec/CPAProxy#27]
I use xcode 7, when i try $ bash ./scripts/build-all.sh 
"
~/Documents/apple/CPAProxy/scripts/build
cp: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/lib/libz.dylib: No such file or directory
Building tor for armv7...
"
open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib

can't find libz.dylib file, only libz.tbd

**Comment by rainwolf** [comment]
This pull request solved it for me
https://github.com/ursachec/CPAProxy/pull/26

**Comment by xiongcaixing1986** [comment]
Thanks!

**Comment by chrisballinger** [comment]
Fixed
