### ISSUE TITLE
compilation issue in build script 

### ISSUE THREAD

**Issue by fxf601244325** [ursachec/CPAProxy#31]
Hi all,

I am trying to compile script by using these commands
$ bash ./scripts/build-all.sh

But I am getting error on this line.I believe there is some issue  in shell file.

```
export OPENSSL_VERSION="1.0.2e"
```

bad url : https://www.openssl.org/source/openssl-1.0.2e.tar.gz

**Comment by chrisballinger** [comment]
Fixed
