### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Stevo420** [ursachec/CPAProxy#46]
I'm using the fork form @rainwolf 
When compiling I get the following error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CPAProxyManager", referenced from:
      type metadata accessor for __ObjC.CPAProxyManager in ViewController.o
  "_OBJC_CLASS_$_CPAConfiguration", referenced from:
      type metadata accessor for __ObjC.CPAConfiguration in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When I remove the Code in the ViewController ([First Steps](https://github.com/ursachec/CPAProxy#-first-steps)) it compiles without problems.

I tried to fix it as described in this post: http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64 but without success...

**Comment by rainwolf** [comment]
I just tried to reproduce your issue with a new project and my fork, I can't reproduce your issue. It should work out of the box if you use cocoapods.
