### ISSUE TITLE
First connection is success, second time fail.

### ISSUE THREAD

**Issue by bucky0970** [ursachec/CPAProxy#56]
Console shows like the previous connection was not release, I check cpamanager, its only has isConnected method, my question is how to disconnect and reconnect?
```
Jan 19 11:09:45.000 [notice] Tor 0.2.9.8 (git-01ab67e38b358ae9) running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2j and Zlib 1.2.8.
Jan 19 11:09:45.000 [notice] Tor 0.2.9.8 (git-01ab67e38b358ae9) running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2j and Zlib 1.2.8.
Jan 19 11:09:45.000 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 19 11:09:45.000 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
```

**Comment by chrisballinger** [comment]
You can't start/stop Tor once it's running because it assumes it's the only thing in the process and will quit your whole app.

**Comment by bucky0970** [comment]
Thanks for reply, so that can I use .isConnected to check? If return true I do data exchange, if false I do initial CPAproxy? Is this algorithm has any Incorrect? Thanks.
