### ISSUE TITLE
Which socks does CPAProxy run up? socks4 or sock5?

### ISSUE THREAD

**Issue by bucky0970** [ursachec/CPAProxy#62]
I use a rtmp module in my project, and when I want go thru CPAProxy, it says "SOCKS negotiation failed". After google that, It says rtmp module only support SOCKS4, can not use SOCKS5. I am not sure which socks is CPAProxy run up.

**Comment by chrisballinger** [comment]
socks5 only

**Comment by bucky0970** [comment]
Can CPAProxy modify to create a SOCKS4 instead or additionally... Or, is there any Tor proxy that create SOCKS4 proxy? Thanks for your reply.
