### ISSUE TITLE
Question integration with UIWebView

### ISSUE THREAD

**Issue by serjooo** [ursachec/CPAProxy#67]
Hello, I was wondering if it would be possible to integrate CPAProxy with UIWebView to make a "Tor Browser". 

Also, I was wondering what is the logic behind this, after you establish a connection with Tor does all network requests made from the app go through the Tor servers? Because I was thinking that UIWebView independently handles loading its requests and receiving responses, how would you make the requests go through the Tor Browser? Thus, would I need to do any additional setting up more than what is mentioned in the document to perform this task.

**Comment by chrisballinger** [comment]
https://github.com/mtigas/OnionBrowser

cheers
