### ISSUE TITLE
cpaProxyManager completion not called in Swift

### ISSUE THREAD

**Issue by ekifox** [ursachec/CPAProxy#72]
```
cpaProxyManager!.setup(
            completion: {
                (socksHost, socksPort, error) in
                    print("connected")
                    print("Connected: host=\(socksHost), port=\(Int(socksPort))")
                    //self.handleCPAProxySetup(withSOCKSHost: socksHost!, socksPort: Int(socksPort))
            },
            progress: {
                (progress, summaryString) in
                    print("\(Int(progress)) \(summaryString)")
            }
)
```

Notifications from the "progress" block are exists, but notifications from the "completion" block do not come!
I have a notice in debug panel that all good, but i dont have a message with "Connected: host..."
```
Sep 02 01:23:39.000 [notice] Bootstrapped 100%: Done
100 Optional("Done")
```

**Comment by rainwolf** [comment]
Is your ```cpaProxyManager``` a variable that lives long enough? Like in an instance variable?
If it's only declared inside a function, then it becomes null after that function exits and that us usually the source of a problem like yours.

**Comment by ekifox** [comment]
Ok, thanks, all works now!
